### ISSUE TITLE
Problem when installing river-extra

### ISSUE THREAD

**Issue by mahabenfares** [online-ml/river-extra#6]
Hello, I am using river for data stream clustering and I need to use clustering metrics, so I use river-extra to have access to clustering metrics. I have a problem when installing river-extra:  it uninstalls the recent version of river and installs the old version of river "0.8.0" so that I can use river-extra.  Is there a way for me to use river-extra but with the recent version of river "0.11.1" without downgrading to version 0.8.0 of river ? Thank you.

ERROR: river-extra 0.8.0 requires river<0.9.0,>=0.8.0, but you have river 0.11.1 which is incompatible.

**Comment by MaxHalford** [comment]
Hey there. Thanks for opening the issue, and apologies for the annoyance.

I believe that if you do `pip install git+https://github.com/online-ml/river-extra` it should work fine. I just tried and it worked for me.

There is a temporary bug when doing `pip install "river[extra]"`, but it will be fixed with River's next release.

I hope that helps! If not let us know.

**Comment by mahabenfares** [comment]
Thank you for your quick return, but even when using pip install git+https://github.com/online-ml/river-extra, It downgrade my version of river to 0.10.1 and I need the latest version of river 0.11.1

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
river-extra 0.11.1 requires river<0.11,>=0.10, but you have river 0.11.1 which is incompatible.

**Comment by MaxHalford** [comment]
Hmm interesting. Can you try again now? I've pinned the version to `river=0.11.1`. It's weird, I expected it to pick the latest version.

**Comment by mahabenfares** [comment]
It worked! Thank you very much.

**Comment by MaxHalford** [comment]
Note for @online-ml/core-devs: each time we make a new release of `river`, let's make a release of `river-extra` for the matching version. Maybe we'll find something smarter in the future.
