### ISSUE TITLE
river-extra is not compatible with river version

### ISSUE THREAD

**Issue by mahabenfares** [online-ml/river-extra#7]
Hello again, 
 I have a problem when I import some metrics from river_extra. I think that this version of river_extra is not compatible with the last version of river 0.11.1 . For example when I import purity metric, this is the error that gives me:

![image](https://user-images.githubusercontent.com/59647660/186407454-3519c816-4ee4-4599-9fc0-819a9916504f.png)

This is an other one when importing cluster:

![image](https://user-images.githubusercontent.com/59647660/186407716-85b2e7f0-b376-44c8-a865-94aeba4e79f7.png)

**Comment by MaxHalford** [comment]
Mmm so sorry about this, I'll look into it.

There haven't been many users of this repo until now, so apologies for you acting as the guinea pig :)

**Comment by MaxHalford** [comment]
Ok try again, it works for me:

```py
from river_extra import metrics

metrics.Purity()
metrics.cluster.BIC()
```

**Comment by mahabenfares** [comment]
Thank you, I tested almost all metrics, there are just 2 metrics that still does not work and need to be updated with the new version of river: CalinskiHarabasz (ssq_based.py) and BIC. 

This is the error that I got:

![image](https://user-images.githubusercontent.com/59647660/186424196-931fc8fd-ec20-460e-8a16-bb0e28629bb6.png)

![image](https://user-images.githubusercontent.com/59647660/186424395-f6476fbc-ab83-4984-a7a6-618ae3154fa6.png)

**Comment by MaxHalford** [comment]
Good catch, fixed. Keep letting me know if there are remaining issues.
